export { executeBrowserJourney } from './executor.ts';
export { evaluateUiDiagnosticsEvidence } from './ui-diagnostics.ts';
export type {
  BrowserActionOutcome,
  BrowserAdapterResult,
  BrowserArtifactCapture,
  BrowserArtifactQuality,
  BrowserArtifactQualityStatus,
  BrowserArtifactType,
  BrowserAutomationPort,
  BrowserBlocker,
  BrowserCapabilityKind,
  BrowserCommandResult,
  BrowserDiagnostic,
  BrowserPortExecutionInput,
  BrowserPortExecutionResult,
  ExecuteBrowserJourneyInput,
  PlannedBrowserAction,
} from './types.ts';
export type {
  BrowserConsoleIssue,
  BrowserNetworkIssue,
  BrowserViewportEvidence,
  BrowserVisualIssue,
  BrowserVisualIssueType,
  EvaluateUiDiagnosticsEvidenceInput,
  UiDiagnosticSeverity,
  UiDiagnosticsBlocker,
  UiDiagnosticsDiagnostic,
  UiDiagnosticsEvidenceResult,
  UiStateMatrixEntry,
  UiStateObservation,
  UiStateObservationStatus,
  UxCapabilityStatus,
} from './ui-diagnostics-types.ts';
